/*
データベース演習I 課題11
クラス：SK1A04
制作者：文家俊
作成日：2023/01/19
*/


/*
  学習環境のピザ屋のデータベースには制約が全く設定されていません。
  テーブル定義書を元に必要な制約の追加をしましょう。
*/

-- 問１：試作品表シートをもとに仮商品番号に主キー(PRIMARY KEY)制約を追加してください。
ALTER TABLE PROTOTYPE ADD PRIMARY KEY( PROTOTYPE_NO );

SHOW COLUMNS FROM PROTOTYPE;

-- 問２：職種表シートをもとに職種番号に主キー制約を職種名にNOT NULL制約を追加してください。
ALTER TABLE JOB MODIFY JOB_NO INT NOT NULL,
				MODIFY JNAME VARCHAR(4) NOT NULL,
				ADD PRIMARY KEY( JOB_NO );

SHOW COLUMNS FROM JOB;

-- 問３：ランク表シートをもとに主キー制約とNOT NULL制約を追加してください。
ALTER TABLE RANKPOINT MODIFY RANK_NAME varchar(6) NOT NULL,
					  MODIFY LO_POINT INT NOT NULL,
					  MODIFY HI_POINT INT NOT NULL,
					  ADD PRIMARY KEY( LO_POINT ) ;

SHOW COLUMNS FROM RANKPOINT;

-- 問４：レシピ表シートをもとに主キー制約とNOT NULL制約を追加してください。
--      ※レシピ表の主キーは商品番号と原材料番号の複合キーになります。
ALTER TABLE RECIPE MODIFY PRODUCT_NO char(4) NOT NULL,
				   MODIFY MATERIAL_NO char(5) NOT NULL,
 				   MODIFY QUANTITY INT NOT NULL;
 				   
ALTER TABLE RECIPE ADD PRIMARY KEY( PRODUCT_NO,MATERIAL_NO );

SHOW COLUMNS FROM RECIPE;

-- 問５：車体管理表シートをもとに必要な制約を追加してください。
ALTER TABLE BIKE MODIFY BIKE_NO CHAR(5) NOT NULL,
				 MODIFY BNAME VARCHAR(50) NOT NULL,
				 MODIFY BUY_DATE DATE NOT NULL,
				 MODIFY STORE_NO CHAR(3) NOT NULL;
				 
ALTER TABLE BIKE ADD PRIMARY KEY( BIKE_NO ) ;

SHOW COLUMNS FROM BIKE;


-- 問６：サイズ表シートをもとに必要な制約と価格差にデフォルト値の設定をしてください。
ALTER TABLE SIZE MODIFY CATEGORY VARCHAR(4) NOT NULL,
				 MODIFY SIZE CHAR(1) NOT NULL,
				 MODIFY DIFF INT NOT NULL DEFAULT 0;
				 
ALTER TABLE SIZE ADD PRIMARY KEY( CATEGORY,SIZE );

SHOW COLUMNS FROM SIZE;

-- 問７：店舗表シートをもとに電話番号のUNIQUE制約を含む必要な制約と
--      デフォルト値の設定をしてください。
ALTER TABLE STORE MODIFY STORE_NO CHAR(3) NOT NULL,
				  MODIFY SNAME VARCHAR(20) NOT NULL,
				  MODIFY HOLIDAY VARCHAR(7) NOT NULL DEFAULT '年中無休',
				  MODIFY STATUS VARCHAR(5) NOT NULL DEFAULT '未オープン';
				  
ALTER TABLE STORE ADD PRIMARY KEY( STORE_NO );
ALTER TABLE STORE ADD UNIQUE( TEL ) ;

SHOW COLUMNS FROM STORE;

-- 問８：原材料表シートをもとに原価のCHECK制約含む必要な制約を追加してください。
ALTER TABLE MATERIAL ADD CHECK( COST >= 0 ),
					 ADD PRIMARY KEY( MATERIAL_NO ),
					 MODIFY MATERIAL_NO char(5) COLLATE utf8mb4_unicode_ci NOT NULL,
					 MODIFY MNAME varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
					 MODIFY ORIGIN varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
					 MODIFY COST int NOT NULL;

SHOW COLUMNS FROM MATERIAL;

-- 問９：新従業員表シートをもとに必要な制約を追加してください。
ALTER TABLE EMPLOYEE ADD CHECK ( SALARY >= 0 ),
					 ADD PRIMARY KEY( EMP_NO ),
					 ADD UNIQUE ( TEL ),
					 MODIFY EMP_NO char(5) COLLATE utf8mb4_unicode_ci NOT NULL,
					 MODIFY ENAME varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
					 MODIFY BIRTHDAY date NOT NULL,
					 MODIFY TEL varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
					 MODIFY ADDRESS varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
					 MODIFY HIREDATE date DEFAULT NULL,
					 MODIFY JOB_NO int DEFAULT NULL,
					 MODIFY RANK_POINT int NOT NULL,
					 MODIFY SALARY int NOT NULL,
					 MODIFY WORK_STORE char(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
					 MODIFY MGR_NO char(5) COLLATE utf8mb4_unicode_ci DEFAULT NULL;

SHOW COLUMNS FROM EMPLOYEE;

-- 問１０：税率表シートをもとに表の作成と共に制約の定義をしてください。
CREATE TABLE TAX(
	TAX INT NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE,
	TAKEOUT_FLG INT NOT NULL
);
	
ALTER TABLE TAX ADD PRIMARY KEY( START_DATE,TAKEOUT_FLG );

SHOW COLUMNS FROM TAX;
